version: '3.9'

services:
  php:
    image: php:8.3-fpm
    container_name: ai-php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - web
      - internal

  nginx:
    image: nginx:stable
    container_name: ai-nginx
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"                      # ✅ DODANE
      - "traefik.http.routers.ai.rule=Host(`ai.localhost`)"
      - "traefik.http.routers.ai.entrypoints=web"
      - "traefik.http.routers.ai.priority=100"
      - "traefik.http.services.ai.loadbalancer.server.port=80"

  mysql:
    image: mysql:8.0
    container_name: ai-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

networks:
  web:
    external: true
  internal:
    driver: bridge

volumes:
  mysql_data:
